#### Customer Feedback Sentiment Analysis for ShopEase Europe
By
Olayemi Balogun

#### Business Introduction
ShopEase Europe is a large online shopping company that sells different products across Europe.
Every day, customers leave reviews, comments, and complaints on the website, social media, and customer support channels. With over a million users each month, there is too much feedback for staff to read manually.
The company wants to understand what customers are saying and how they feel. To maintain high customer satisfaction and improve service delivery.

#### Problem Statement
- Thousands of reviews are received every day, making it difficult for employees to read and analyze them all.
- Different analysts may interpret the same review differently, leading to inconsistent results.
- Although feedback is available, it takes too much time to turn it into useful business actions.

#### Project Objectives

- Clean and prepare customer reviews written in different languages.
- Build machine learning models that can predict customer sentiment.
- Identify the main reasons customers are happy or unhappy.
- Create summaries of customer opinions.
- Display results in an interactive dashboard.

##### Import the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from langdetect import detect
from langdetect.lang_detect_exception import LangDetectException
import re
import spacy
import nltk
from nltk.corpus import stopwords
import plotly.express as px

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\balog\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\balog\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

##### Load the dataset

In [2]:
df = pd.read_csv(r'C:\Users\balog\OneDrive\Documents\Olayemi\Intership\Customer Feedback Analysis\Data\reviews.csv')
df.head()

,review_id,product_category,timestamp,country,rating,review,sentiment
0,REV-50BCBCD9,Sports,2024-09-16 13:44:26+00:00,US,1,"I registered on the website, tried to order a ...",Negative
1,REV-6D2B2651,Toys,2024-09-16 18:26:46+00:00,GB,1,Had multiple orders one turned up and driver h...,Negative
2,REV-F7E80372,Toys,2024-09-16 21:47:39+00:00,GB,1,I informed these reprobates that I WOULD NOT B...,Negative
3,REV-ED2B173F,Sports,2024-09-17 07:15:49+00:00,AU,1,I have bought from Amazon before and no proble...,Negative
4,REV-E48A7AB9,Fashion,2024-09-16 18:37:17+00:00,GB,1,If I could give a lower rate I would! I cancel...,Negative

##### Data Overview

In [3]:
print("="*50)
print("DATASET OVERVIEW")
print("="*50)

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")
print(f"Shape: {df.shape}")

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nUnique Values:")
print(df.nunique())

for col in df.columns:
    print(f"\n{col}")
    print(df[col].unique())

print("\nFirst 5 Rows:")
print(df.head())

==================================================
DATASET OVERVIEW
==================================================
Rows: 21055
Columns: 7
Shape: (21055, 7)

Column Names:
['review_id', 'product_category', 'timestamp', 'country', 'rating', 'review', 'sentiment']

Data Types:
review_id           object
product_category    object
timestamp           object
country             object
rating               int64
review              object
sentiment           object
dtype: object

Missing Values:
review_id           0
product_category    0
timestamp           0
country             1
rating              0
review              0
sentiment           0
dtype: int64

Duplicate Rows:
0

Unique Values:
review_id           21055
product_category        7
timestamp           21054
country               148
rating                  5
review              20407
sentiment               3
dtype: int64

review_id
['REV-50BCBCD9' 'REV-6D2B2651' 'REV-F7E80372' ... 'REV-9305C28A'
 'REV-40867447' 'REV-4765654E']

product_category
['Sports' 'Toys' 'Fashion' 'Beauty' 'Food & Grocery' 'Home & Living'
 'Electronics']

timestamp
['2024-09-16 13:44:26+00:00' '2024-09-16 18:26:46+00:00'
 '2024-09-16 21:47:39+00:00' ... '2008-09-16 13:05:05+00:00'
 '2008-04-28 11:09:05+00:00' '2007-08-27 17:25:01+00:00']

country
['US' 'GB' 'AU' 'JP' 'CA' 'ZA' 'IN' 'BE' 'AE' 'NZ' 'IL' 'NL' 'SE' 'DK'
 'JM' 'DE' 'MY' 'FR' 'ES' 'IT' 'PR' 'KW' 'PK' 'PT' 'TW' 'IE' 'DO' 'TR'
 'HK' 'ME' 'FI' 'CH' 'CO' 'CY' 'PA' 'ID' 'EG' 'HR' 'BR' 'GR' 'PL' 'NI'
 'TH' 'SK' 'CN' 'VG' 'BH' 'CZ' 'GG' 'AT' 'MA' 'CV' 'GE' 'LT' 'MT' 'MC'
 'RU' 'UA' 'AG' 'OM' 'VI' 'VN' 'KH' 'NG' 'QA' 'NO' 'GH' 'CR' 'BO' 'MQ'
 'KE' 'PE' 'BS' 'RO' 'JE' 'PH' 'DZ' 'RS' 'AZ' 'AF' 'SA' 'AM' 'MV' 'EE'
 'HU' 'CM' 'PG' 'AR' 'BG' 'MX' 'LV' 'SL' 'CD' 'MO' 'GI' 'LU' 'AO' 'BD'
 'KR' 'KZ' 'ET' 'FJ' 'SG' 'UG' 'SR' 'EC' 'BY' 'SI' 'TN' 'HN' 'VE' 'NP'
 'BB' 'CW' 'GF' 'BZ' 'CL' 'GT' 'KG' 'MG' 'IM' 'TT' 'PY' 'LK' 'BA' nan 'LA'
 'TZ' 'IQ' 'BQ' 'GY' 'MN' 'IS' 'MD' 'UY' 'SO' 'RW' 'MU' 'BM' 'LB' 'IR'
 'JO' 'SV' 'BW' 'AD' 'CI' 'ZM' 'MK' 'MM']

rating
[1 5 2 4 3]

review
["I registered on the website, tried to order a laptop, entered all the details, but instead of charging me and sending the product, they froze my account, demanding various verification documents. I sent them over. They said they would review them within 24 hours. In reality, it's been a week, and no one can help or give any (truthful) estimate of when it will be resolved; they just tell me to 'wait.' I've never seen such a horrible marketplace in my life. I hope those who came up with this can't buy food in a store, receiving a 'document review request' that takes forever to process."
 "Had multiple orders one turned up and driver had to phone as no door number on packaging, then waited all day for second package to get a message saying couldn't deliver as no number on packaging, 12 hours waiting in now don't even know when I'm getting delivery. Terrible will never use again"
 'I informed these reprobates that I WOULD NOT BE IN as I was going to visit a sick relative, they told me they were going to send a OTP, I told them I could not receive it as I was travelling a long way on the underground, their reply was don’t worry we can text. I pointed out I can’t receive texts EITHER!!They said parcel was on its way so couldn’t stop it. I pointed out I WOULD NOT WANT IT as, I had PERMANENTLY CLOSED my account!The driver came whilst I was out and failed to even follow my settings info that said to deliver to a specific neighbour if I was out, since then my account has now been deleted'
 ...
 'I always find myself going back to amazon becouse there prices are so good, however i have had several bad experiences while buying from resellers that are allowed to advertise on there site, with one delivery taking two weeks to arrive, the real sting in the tail was that the HD-dvd went bust a couple of weeks later'
 'I have placed an abundance of orders with Amazon during the last couple of years, none of which gave me any trouble. I have been in contact with customer support a couple of times when the delivery failed because of my own mistakes - in each of those cases Amazon was very friendly and the end result was always positive. Their web-page is perhaps the best among any retailers out there. There are a couple of negative points when shopping at Amazon from Denmark:\r* Most of the products are unavailable to danes\r* "Supersaver" shipping is never available\r* Amazon complies stringently with customs regulations which means you have to count in a customs fee that can sometimes be avoided with other online shops\r I hope all of those points are going to be addressed in the future, with a danish or scandinavian Amazon.\r All in all though, one of the best shops online.'
 "those goods i've ordered by Amazon.com, have been delivered in good order, even as it is an international delivery, since i live in Denmark, I expected there would be some weeks before i would get my goods. the only thing i find a bit frustrating at times is, sometimes, the late announcement of goods that are out of stock. otherwise very good conditions."]

sentiment
['Negative' 'Positive' 'Neutral']

First 5 Rows:
      review_id product_category                  timestamp country  rating  \
0  REV-50BCBCD9           Sports  2024-09-16 13:44:26+00:00      US       1
1  REV-6D2B2651             Toys  2024-09-16 18:26:46+00:00      GB       1
2  REV-F7E80372             Toys  2024-09-16 21:47:39+00:00      GB       1
3  REV-ED2B173F           Sports  2024-09-17 07:15:49+00:00      AU       1
4  REV-E48A7AB9          Fashion  2024-09-16 18:37:17+00:00      GB       1

                                              review sentiment
0  I registered on the website, tried to order a ...  Negative
1  Had multiple orders one turned up and driver h...  Negative
2  I informed these reprobates that I WOULD NOT B...  Negative
3  I have bought from Amazon before and no proble...  Negative
4  If I could give a lower rate I would! I cancel...  Negative

       OVERVIEW
     - The dataset contains 21,055 rows (customer reviews) and 7 columns.
     - 1 missig value in the column 'country' and no duplicated rows.
     - There are 148 countries, 7 product categories, rating is from 1 to 5, 20,407 unique review texts.
     - The timestamp column is stored as an object instead of a date format.
     - Clean sentiment labels and no inconsistency.
     - Multilingual reviews.

##### Data Report

In [4]:
data_report = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values,
    "Data Quality Issues": ["No issues", "No inconsistencies", "Convert to datetime", "Standardized codes", 
                     "Valid values", "Repetitive texts", "Validated labels"] 
})

data_report

,Column Name,Data Type,Missing Values,Unique Values,Data Quality Issues
0,review_id,object,0,21055,No issues
1,product_category,object,0,7,No inconsistencies
2,timestamp,object,0,21054,Convert to datetime
3,country,object,1,148,Standardized codes
4,rating,int64,0,5,Valid values
5,review,object,0,20407,Repetitive texts
6,sentiment,object,0,3,Validated labels